# Generated by Django 2.1.2 on 2018-11-12 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('idActor', models.AutoField(db_column='idActor', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nameActor', max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_nameActor', max_length=45, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birthActor', null=True)),
                ('description', models.CharField(blank=True, db_column='descriptionActor', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('idDirector', models.AutoField(db_column='idDirector', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('idGenre', models.AutoField(db_column='idGenre', primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, db_column='genre', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='descriptionGenre', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('idimage', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(db_column='idMood', primary_key=True, serialize=False)),
                ('mood', models.CharField(blank=True, db_column='mood', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='descriptionMood', max_length=45, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'mood',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(db_column='idMovie', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titleMovie', max_length=100)),
                ('pub_year', models.IntegerField(db_column='pub_yearMovie')),
                ('duration', models.IntegerField(db_column='durationMovie')),
                ('description', models.CharField(db_column='descriptionMovie', max_length=2000)),
                ('country', models.CharField(db_column='countryMovie', max_length=50)),
                ('trailer_url', models.CharField(blank=True, db_column='trailer_urlMovie', max_length=200, null=True)),
                ('logo', models.CharField(blank=True, db_column='logoMovie', max_length=200, null=True)),
                ('imdb_score', models.FloatField(blank=True, db_column='imdb_scoreMovie', max_length=2.2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='mdvapp.Actor')),
                ('director', models.ManyToManyField(to='mdvapp.Director')),
                ('genre', models.ManyToManyField(to='mdvapp.Genre')),
                ('images', models.ManyToManyField(to='mdvapp.Images')),
                ('mood', models.ManyToManyField(related_name='moods', to='mdvapp.Mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
