# Generated by Django 2.1.2 on 2018-11-13 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdvapp', '0002_auto_20181113_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idReview', models.AutoField(db_column='idReview', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titleReview', max_length=150)),
                ('content', models.CharField(db_column='contentReview', max_length=4000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdvapp.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
