# Generated by Django 2.1.2 on 2018-11-13 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdvapp', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMovie',
            fields=[
                ('idRating', models.AutoField(db_column='idRating', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdvapp.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratingMovie',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ratingmovie',
            unique_together={('user', 'movie')},
        ),
    ]
