# Generated by Django 2.1.2 on 2018-11-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0004_auto_20181113_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmovie',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
