# Generated by Django 2.1.2 on 2018-11-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdvapp', '0007_auto_20181113_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieList',
            fields=[
                ('idUserMovieList', models.AutoField(db_column='idUserMovieList', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('movies', models.ManyToManyField(to='mdvapp.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userMovieList',
            },
        ),
        migrations.CreateModel(
            name='UserMovieListComment',
            fields=[
                ('idUserMovieListComment', models.AutoField(db_column='idUserMovieListComment', primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userMovieList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdvapp.UserMovieList')),
            ],
            options={
                'db_table': 'userMovieListComment',
            },
        ),
        migrations.CreateModel(
            name='UserMovieListLike',
            fields=[
                ('idUserMovieListLike', models.AutoField(db_column='idUserMovieListLike', primary_key=True, serialize=False)),
                ('like', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userMovieList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdvapp.UserMovieList')),
            ],
            options={
                'db_table': 'userMovieListLike',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usermovielistlike',
            unique_together={('user', 'userMovieList')},
        ),
        migrations.AlterUniqueTogether(
            name='usermovielistcomment',
            unique_together={('user', 'userMovieList')},
        ),
    ]
