# Generated by Django 2.1.2 on 2018-11-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0008_auto_20181114_0200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovielistcomment',
            unique_together=set(),
        ),
    ]
