# Generated by Django 2.1.2 on 2018-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0009_auto_20181114_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='description',
            field=models.CharField(blank=True, db_column='descriptionMood', max_length=400, null=True),
        ),
    ]
