# Generated by Django 2.1.2 on 2018-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0010_auto_20181122_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
