# Generated by Django 2.1.2 on 2018-12-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0015_movie_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
