# Generated by Django 2.1.2 on 2019-01-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0016_movie_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
