# Generated by Django 2.1.2 on 2019-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0017_auto_20190128_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(db_column='idActor', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='nameActor', max_length=455, null=True)),
            ],
            options={
                'db_table': 'ipAddress',
            },
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, db_column='genre', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='visits',
            field=models.ManyToManyField(to='mdvapp.IPAddress'),
        ),
    ]
