# Generated by Django 2.1.2 on 2019-01-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0019_auto_20190130_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='visits',
            new_name='visit',
        ),
    ]
