# Generated by Django 2.1.2 on 2019-01-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0020_auto_20190130_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='visit',
            field=models.ManyToManyField(null=True, to='mdvapp.IPAddress'),
        ),
    ]
