# Generated by Django 2.1.2 on 2019-01-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0021_auto_20190130_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(db_column='nameActor', max_length=45, unique=True),
        ),
    ]
