# Generated by Django 2.1.2 on 2019-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0022_auto_20190130_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='visit',
            field=models.ManyToManyField(blank=True, null=True, to='mdvapp.IPAddress'),
        ),
    ]
