# Generated by Django 2.1.2 on 2019-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0024_auto_20190130_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='search_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
