# Generated by Django 2.1.2 on 2019-02-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0025_actor_search_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(db_column='titleReview', max_length=50),
        ),
    ]
