# Generated by Django 2.1.2 on 2019-02-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0027_auto_20190205_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('idFeedback', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('ip_address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mdvapp.IPAddress')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
