# Generated by Django 2.1.2 on 2019-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0030_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='search_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
