# Generated by Django 2.1.2 on 2019-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0032_director_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
