# Generated by Django 2.1.2 on 2019-02-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdvapp', '0035_auto_20190207_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
